apiVersion: v1
imagePullSecrets:
- name: iron-bank-bot-secret
kind: ServiceAccount
metadata:
  name: rescale-github-bot
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::152586189762:role/TektonAWSKaniko-role
secrets:
- name: rescale-org-github-bot-key